<?php
require_once __DIR__.'/../vendor/autoload.php';
include_once(__DIR__.'/../Controller/ProductController.php');
include_once(__DIR__.'/../Controller/UserController.php');
use app\Controllers\ProductController;
use app\Controllers\UserController;
use app\Router;
$ProdController=new ProductController();
$UserController = new UserController();
$router = new Router();
$router->get('/', [$ProdController, 'index']);
$router->get('/products', [$ProdController, 'index']);
$router->get('/products/product_detail', [$ProdController, 'product_detail']);
$router->get('/users/register', [$UserController, 'register']);
$router->post('/users/register', [$UserController, 'register']);
$router->get('/users/login', [$UserController, 'login']);
$router->post('/users/login', [$UserController, 'login']);
$router->post('/users/logout', [$UserController, 'logout']);
$router->get('/users/logout', [$UserController, 'logout']);
$router->post('/products/shoppingcart', [$ProdController, 'shoppingcart']);
$router->get('/products/shoppingcart', [$ProdController, 'shoppingcart']);
$router->get('/products/removecartindex', [$ProdController, 'removecartindex']);
$router->post('/products/removecartindex', [$ProdController, 'removecartindex']);
$router->get('/products/addtocart', [$ProdController, 'addtocart']);
$router->post('/products/addtocart', [$ProdController, 'addtocart']);
$router->post('/products/inscreasequantity', [$ProdController, 'inscreasequantity']);
$router->get('/products/inscreasequantity', [$ProdController, 'inscreasequantity']);
$router->post('/products/checkout', [$ProdController, 'checkout']);
$router->get('/products/checkout', [$ProdController, 'checkout']);
$router->get('/products/shop', [$ProdController, 'shop']);
$router->post('/products/shop', [$ProdController, 'shop']);
$router->get('/paypal/payment_status', [$ProdController, 'paypal']);
$router->post('/paypal/payment_status', [$ProdController, 'paypal']);
$router->resolve();
?>